### ISSUE TITLE
Error while processing a video

### ISSUE THREAD

**Issue by reshmastadas** [wmuron/motpy#6] opened 2021-01-27 02:43 UTC
Hi,

I am using a combination of yolo v4 tiny and motpy to track people in a video. However, after processing successfully for few seconds, the code fails and gives the following error:

`/home/user1/anaconda3/envs/people_counting_windows/lib/python3.8/site-packages/motpy/metrics.py:23: RuntimeWarning: invalid value encountered in true_divide
  iou = val_inter / (val_b1 + np.transpose(val_b2) - val_inter)
Traceback (most recent call last):
  File "motpy_t.py.py", line 101, in <module>
    tracker.step(detections)
  File "/home/user1/anaconda3/envs/people_counting_windows/lib/python3.8/site-packages/motpy/tracker.py", line 279, in step
    matches = self.matching_fn(self.trackers, detections)
  File "/home/user1/anaconda3/envs/people_counting_windows/lib/python3.8/site-packages/motpy/tracker.py", line 201, in __call__
    return match_by_cost_matrix(
  File "/home/user1/anaconda3/envs/people_counting_windows/lib/python3.8/site-packages/motpy/tracker.py", line 133, in match_by_cost_matrix
    row_ind, col_ind = scipy.optimize.linear_sum_assignment(cost_mat)
  File "/home/user1/anaconda3/envs/people_counting_windows/lib/python3.8/site-packages/scipy/optimize/_lsap.py", line 93, in linear_sum_assignment
    raise ValueError("matrix contains invalid numeric entries")
ValueError: matrix contains invalid numeric entries
`
Kindly help me with this.

**Comment by wmuron** [comment] 2021-01-27 21:31
Please upload the example detections causing the exception, I'll try to reproduce it.

**Comment by PPakalns** [comment] 2021-03-30 12:22
Hi, I had the same error.

 It looks like it is raised in cases when bounding box coordinates are inclusive and the width or height of the bounding box is one. 

Then the bounding box area union is calculated to be zero and division by zero is not defined.

This library should specify if coordinates are inclusive, exclusive. If coordinates are inclusive, this bug should be fixed in iou calculation function by simply appending one to the largest bounding box coordinate in all dimensions.

**Comment by haviduck** [comment] 2021-06-18 21:15
isnt that the same issue SORT had? with linear sum, think he wrote his own instead of using sks or spicy

**Comment by reshmastadas** [comment] 2021-06-19 01:11
Sorry for delayed reply. In my case it happened soon after the video got
over.

**Comment by haviduck** [comment] 2021-06-19 01:33
yeah im pretty sure its because you pass negative numbers. can you check? and verify that you astype int32 and not uint32 in your loop. if it happens after the video is done, its probably an empty list which crashes limear sum.

either way, this should help:
https://github.com/wmuron/motpy/blob/be8fb9fb0a010a1cd1f8a8751a7001f80366f724/examples/2d_multi_object_tracking.py#L34


put this above that line (or something along the line of):
track.score= track.score.astype(np.int32)

**Comment by haviduck** [comment] 2021-06-19 01:58
yeah its either negative numbers from faulty detection or empty values

https://github.com/wmuron/motpy/blob/be8fb9fb0a010a1cd1f8a8751a7001f80366f724/examples/2d_multi_object_tracking.py#L34
add this above score
track=track.astype(np.int32)

**Comment by wmuron** [comment] 2021-09-21 20:58
@reshmastadas  @haviduck If you have an example recreating the issue, please add a test and we can try to fix it in next release.

**Comment by haviduck** [comment] 2021-09-21 22:33
> @reshmastadas @haviduck If you have an example recreating the issue, please add a test and we can try to fix it in next release.

yeah absolutely. but im currently facing generic issues with how i pass my bboxes in various trackers so im studying wth im doing wrong.  will provide an eaxmple as soon as i get my head above water so i know exactly what im talking about..

**Closed as completed** 2022-01-28 21:24 UTC
